# Use official Node.js LTS image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the app
COPY orders.js ./ 


# Expose port
EXPOSE 3002

# Start the service
CMD ["node", "orders.js"]
